# .pre-commit-config.yaml

repos:
  # Black - code formatter
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

   # isort - import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # mypy - type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        name: mypy type check
        entry: mypy
        language: python
        types: [ python ]
        files: ^ai_service/.*\.py$
        args: ["--strict", "--ignore-missing-imports"]

  # Flake8 - Python style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^ai_service/.*\.py$

  # Whitespace fixer
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: debug-statements
